name: Generate coverage on CI

on:
  push:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - lts/gallium
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn format:ci
      - run: yarn lint:ci
      - run: yarn typecheck
      - name: Test
        run: yarn test:cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}