name: Pull request checks

on:
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    name: Run checks for pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
      - uses: actions/cache@v2.1.7
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn format:ci
      - run: yarn lint:ci
      - run: yarn typecheck
      - run: yarn test