name: Pull request checks

on:
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
      - run: yarn install --frozen-lockfile
      - name: Format check
        run: yarn format:ci
      - name: Linter
        run: yarn lint:ci
      - name: Typecheck
        run: yarn typecheck
      - name: Jest
        run: yarn test
